baseURL = "https://tics.site"
languageCode = "en-us"
title = "TICS - Topics on Internet Censorship and Surveillance"

theme = "mondrian"
# Theme config
[taxonomies]
  tag = "tags"

[params]
  showHeader = true
  showTags = true
  debug = false
  [params.colors]
    post = "orangered"
    posts = "gold"
    page = "blue"
